# Generated by Django 4.2.1 on 2023-05-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x2', models.BooleanField()),
                ('x6', models.BooleanField()),
                ('x11', models.IntegerField()),
                ('x12', models.IntegerField()),
                ('x18', models.IntegerField()),
                ('x19', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=124)),
                ('last_name', models.CharField(max_length=124)),
                ('age', models.IntegerField()),
                ('region', models.CharField(max_length=124)),
                ('district', models.CharField(max_length=124)),
            ],
        ),
    ]
