# Generated by Django 4.2.1 on 2023-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_params_options_alter_users_options_params_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='x11',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='params',
            name='x12',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='params',
            name='x18',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='params',
            name='x19',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
