# Generated by Django 4.2.1 on 2023-06-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_params_x11_alter_params_x12_alter_params_x18_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='params',
            name='user',
        ),
    ]
